In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os
import sys
# os.makedirs('../plots', exist_ok=True)

In [4]:
df = pd.read_csv('../data/nyc_311_requests_jul2025_jun2026.csv')    
df.head()

,unique_key,created_date,closed_date,agency,complaint_type,descriptor,borough,incident_zip,status
0,65568225,2025-07-15T15:30:51.000,2025-07-31T14:14:57.000,DOHMH,Rodent,Rat Sighting,BROOKLYN,11219.0,Closed
1,65568932,2025-07-15T10:06:12.000,2025-07-15T10:51:29.000,NYPD,Illegal Parking,Commercial Overnight Parking,QUEENS,11692.0,Closed
2,65567550,2025-07-15T19:56:00.000,2025-07-15T21:01:00.000,DEP,Water System,Hydrant Running Full (WA4),QUEENS,11374.0,Closed
3,65567944,2025-07-15T08:24:53.000,2025-07-15T08:54:40.000,NYPD,Noise - Residential,Banging/Pounding,STATEN ISLAND,10306.0,Closed
4,65567116,2025-07-15T12:49:30.000,2025-07-22T14:28:31.000,DOT,Sidewalk Condition,Broken Sidewalk,MANHATTAN,10003.0,Closed

Step 1- Convert datate to datetime

In [5]:

df['created_date'] = pd.to_datetime(df['created_date'])
df['closed_date'] = pd.to_datetime(df['closed_date'])
df.head()

,unique_key,created_date,closed_date,agency,complaint_type,descriptor,borough,incident_zip,status
0,65568225,2025-07-15 15:30:51,2025-07-31 14:14:57,DOHMH,Rodent,Rat Sighting,BROOKLYN,11219.0,Closed
1,65568932,2025-07-15 10:06:12,2025-07-15 10:51:29,NYPD,Illegal Parking,Commercial Overnight Parking,QUEENS,11692.0,Closed
2,65567550,2025-07-15 19:56:00,2025-07-15 21:01:00,DEP,Water System,Hydrant Running Full (WA4),QUEENS,11374.0,Closed
3,65567944,2025-07-15 08:24:53,2025-07-15 08:54:40,NYPD,Noise - Residential,Banging/Pounding,STATEN ISLAND,10306.0,Closed
4,65567116,2025-07-15 12:49:30,2025-07-22 14:28:31,DOT,Sidewalk Condition,Broken Sidewalk,MANHATTAN,10003.0,Closed

Step 2 - Fix Zip codes: float -->5-char string

In [6]:
df['incident_zip'] = df['incident_zip'].astype('Int64').astype('string').str.zfill(5)
df.head()

,unique_key,created_date,closed_date,agency,complaint_type,descriptor,borough,incident_zip,status
0,65568225,2025-07-15 15:30:51,2025-07-31 14:14:57,DOHMH,Rodent,Rat Sighting,BROOKLYN,11219,Closed
1,65568932,2025-07-15 10:06:12,2025-07-15 10:51:29,NYPD,Illegal Parking,Commercial Overnight Parking,QUEENS,11692,Closed
2,65567550,2025-07-15 19:56:00,2025-07-15 21:01:00,DEP,Water System,Hydrant Running Full (WA4),QUEENS,11374,Closed
3,65567944,2025-07-15 08:24:53,2025-07-15 08:54:40,NYPD,Noise - Residential,Banging/Pounding,STATEN ISLAND,10306,Closed
4,65567116,2025-07-15 12:49:30,2025-07-22 14:28:31,DOT,Sidewalk Condition,Broken Sidewalk,MANHATTAN,10003,Closed